//* src/constants/appErrorCode.ts

/**
 * Centralized application error codes.
 *
 * @readonly
 * @enum {string}
 */
const appErrorCode = Object.freeze({
	// General
	ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
	INTERNAL_ERROR: "INTERNAL_ERROR",
	RATE_LIMITED: "RATE_LIMITED",
	DUPLICATE_KEY: "DUPLICATE_KEY",
	EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",

	// Validation
	VALIDATION_ERROR: "VALIDATION_ERROR",

	// Auth
	UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
	INSUFFICIENT_ROLE: "INSUFFICIENT_ROLE",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
	EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
	INVALID_OR_EXPIRED_TOKEN: "INVALID_OR_EXPIRED_TOKEN",

	// OAuth (Google sign-in)
	INVALID_ID_TOKEN: "INVALID_ID_TOKEN",
	GOOGLE_EMAIL_NOT_VERIFIED: "GOOGLE_EMAIL_NOT_VERIFIED",
	PROVIDER_MISMATCH: "PROVIDER_MISMATCH",

	// CSRF
	CSRF_ORIGIN_MISMATCH: "CSRF_ORIGIN_MISMATCH",

	// Course domain
	RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
	COURSE_NOT_FOUND: "COURSE_NOT_FOUND",
	SECTION_NOT_FOUND: "SECTION_NOT_FOUND",
	LESSON_NOT_FOUND: "LESSON_NOT_FOUND",
	STUDENT_NOT_FOUND: "STUDENT_NOT_FOUND",
	COURSE_HAS_ENROLLMENTS: "COURSE_HAS_ENROLLMENTS",
	COURSE_NOT_PUBLISHABLE: "COURSE_NOT_PUBLISHABLE",

	// Media / enrollment
	NOT_ENROLLED: "NOT_ENROLLED",
	VIDEO_NOT_FOUND: "VIDEO_NOT_FOUND",
	TRAILER_NOT_FOUND: "TRAILER_NOT_FOUND",
	UPLOAD_INCOMPLETE: "UPLOAD_INCOMPLETE",

	// Payments
	ALREADY_ENROLLED: "ALREADY_ENROLLED",
	CHECKOUT_SESSION_NOT_FOUND: "CHECKOUT_SESSION_NOT_FOUND",
	WEBHOOK_SIGNATURE_INVALID: "WEBHOOK_SIGNATURE_INVALID",
	PAYMENT_AMOUNT_MISMATCH: "PAYMENT_AMOUNT_MISMATCH",
});

export default appErrorCode;
