//* src/constants/appErrorCode.ts

/**
 * Centralized application error codes.
 *
 * @readonly
 * @enum {string}
 */
const appErrorCode = Object.freeze({
	// General
	ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
	INTERNAL_ERROR: "INTERNAL_ERROR",
	RATE_LIMITED: "RATE_LIMITED",
	DUPLICATE_KEY: "DUPLICATE_KEY",

	// Validation
	VALIDATION_ERROR: "VALIDATION_ERROR",

	// Auth
	UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
	INSUFFICIENT_ROLE: "INSUFFICIENT_ROLE",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
	ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",

	// Course domain
	RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
	COURSE_NOT_FOUND: "COURSE_NOT_FOUND",
	SECTION_NOT_FOUND: "SECTION_NOT_FOUND",
	LESSON_NOT_FOUND: "LESSON_NOT_FOUND",
	STUDENT_NOT_FOUND: "STUDENT_NOT_FOUND",
	COURSE_HAS_ENROLLMENTS: "COURSE_HAS_ENROLLMENTS",

	// Media / enrollment
	NOT_ENROLLED: "NOT_ENROLLED",
	VIDEO_NOT_FOUND: "VIDEO_NOT_FOUND",
	TRAILER_NOT_FOUND: "TRAILER_NOT_FOUND",
	UPLOAD_INCOMPLETE: "UPLOAD_INCOMPLETE",

	// Payments
	ALREADY_ENROLLED: "ALREADY_ENROLLED",
	CHECKOUT_SESSION_NOT_FOUND: "CHECKOUT_SESSION_NOT_FOUND",
	PAYMENT_NOT_COMPLETED: "PAYMENT_NOT_COMPLETED",
	WEBHOOK_SIGNATURE_INVALID: "WEBHOOK_SIGNATURE_INVALID",
	PAYMENT_AMOUNT_MISMATCH: "PAYMENT_AMOUNT_MISMATCH",
});

export default appErrorCode;
